---

- name: Install psql
  ansible.builtin.apt:
    name: postgresql-13
    state: present
  become: true

- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present
    force_apt_get: true
  become: true

- name: Install tldr
  ansible.builtin.apt:
    name: tldr
    state: present
    force_apt_get: true
  become: true

- name: Install nvim build prerequisites
  ansible.builtin.apt:
    pkg:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
    state: present
    force_apt_get: true
  become: true

- name: Checkout neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: "{{ defaults.home }}/neovim"
    version: stable
    force: true

- name: Make cmake shit
  community.general.make:
    target: install
    chdir: "{{ defaults.home }}/neovim"
    params:
      CMAKE_EXTRA_FLAGS: "-DCMAKE_INSTALL_PREFIX={{ defaults.home }}/neovim"

- name: Export neovim to path
  ansible.builtin.shell:
    cmd: 'export PATH=$HOME/neovim/bin:$PATH'

- name: Install ghcup required packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - curl
      - libffi-dev
      - libffi8ubuntu1
      - libgmp-dev
      - libgmp10
      - libncurses-dev
      - libncurses5
      - libtinfo5
      - libpq-dev
    state: present
    force_apt_get: true
  become: true

- name: Install ghcup
  ansible.builtin.shell: 'set -o pipefail && curl --proto =https --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_GHC_VERSION=8.8.4 BOOTSTRAP_HASKELL_CABAL_VERSION=latest BOOTSTRAP_HASKELL_INSTALL_STACK=1 BOOTSTRAP_HASKELL_INSTALL_HLS=1 BOOTSTRAP_HASKELL_ADJUST_BASHRC=P sh'

- name: Install fish
  ansible.builtin.apt:
    name: fish
    state: present
  become: true

- name: Set fish as default shell
  ansible.builtin.shell: 'chsh -s $(which fish)'
