---

- name: "Update cache"
  ansible.builtin.apt:
    update_cache:  true

- name: Install psql
  ansible.builtin.apt:
    name: postgresql-14
    state: present
  become: true

- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present
    force_apt_get: true
  become: true

- name: Install tldr
  ansible.builtin.apt:
    name: tldr
    state: present
    force_apt_get: true
  become: true

- name: Install nvim build prerequisites
  ansible.builtin.apt:
    pkg:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
    state: present
    force_apt_get: true
  become: true

- name: Checkout neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz"
    dest: "{{ defaults.home }}/neovim"
    mode: "0440"

- name: Export neovim to path
  ansible.builtin.shell:
    cmd: 'export PATH=$HOME/neovim/nvim-linux64/bin:$PATH'

- name: Install ghcup required packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - curl
      - libffi-dev
      - libffi8ubuntu1
      - libgmp-dev
      - libgmp10
      - libncurses-dev
      - libncurses5
      - libtinfo5
      - libpq-dev
    state: present
    force_apt_get: true
  become: true

- name: Install ghcup
  ansible.builtin.shell: 'curl --proto =https --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_GHC_VERSION=8.8.4 BOOTSTRAP_HASKELL_CABAL_VERSION=latest BOOTSTRAP_HASKELL_INSTALL_STACK=1 BOOTSTRAP_HASKELL_INSTALL_HLS=1 BOOTSTRAP_HASKELL_ADJUST_BASHRC=P sh'

- name: Install docker dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: true
    force_apt_get: true

- name: Add GPG Key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
    force_apt_get: true
