---
- name: Install fish
  ansible.builtin.apt:
    name: fish
    state: present
  become: true

- name: "Set Fish as the default shell"
  ansible.builtin.shell: "chsh -s /usr/bin/fish {{ ansible_env.USER }}"
  become: true

- name: "Check if nerd fonts are installed"
  ansible.builtin.stat:
    path: "/usr/local/share/fonts/NerdFonts"
  register: "fonts"

- name: "Clone nerd fonts repo"
  ansible.builtin.git:
    repo: 'https://github.com/ryanoasis/nerd-fonts'
    dest: '/tmp/nerd-fonts'
    clone: true
    depth: 1
  when: not fonts.stat.exists

- name: "Install nerd fonts"
  become: true
  ansible.builtin.command: "/tmp/nerd-fonts/install.sh -S"
  when: not fonts.stat.exists

- name: "Check if Oh My Fish is installed"
  ansible.builtin.stat:
    path: "{{ home }}/.local/share/omf"
  register: "omf"

- name: "Clone oh-my-fish repo"
  ansible.builtin.git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: true
  when: not omf.stat.exists

- name: "Install oh-my-fish"
  ansible.builtin.command: "/tmp/omf/bin/install -y --offline --noninteractive"
  when: not omf.stat.exists

- name: "Install Bass with Oh My Fish"
  ansible.builtin.shell: "omf install bass"
  args:
    executable: "/usr/bin/fish"

- name: "Install bob the fish"
  ansible.builtin.shell: "omf install bobthefish"
  args:
    executable: "/usr/bin/fish"
